<!-- saved from url=(0068)http://web.ishuilian.com/apiserver/doc/html/5d4a8428886a640078ec2ff2 -->
<html data-server-rendered="true"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><title>委托代扣还款协议</title><style>
    td {
      border-left: 1px solid #000000 !important;
      border-top: 1px solid #000000 !important;
    }
    table {
      border-bottom: 1px solid #000000 !important;
      border-right: 1px solid #000000 !important;
    }

    body {
      font: '12px/1.5 Microsoft YaHei,Heiti SC,PingFang SC,tahoma,arial,Hiragino Sans GB,&quot;\5B8B\4F53&quot;,sans-serif';
      padding: 20px;
    }
  </style></head>  <body><div class="editor"><div class="Section0">
<p class="20" style="text-align: center;" align="center"><strong><span style="font-family: 微软雅黑; font-size: 14pt;"><span style="font-family: 微软雅黑;">委托代扣还款协议</span></span></strong></p>
<p class="MsoNormal" style="margin-left: 0.0000pt; text-indent: 21.0000pt; mso-char-indent-count: 2.0000;"><span style="mso-spacerun: &#39;yes&#39;; font-family: 微软雅黑; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 微软雅黑;">智莲（北京）</span></span><span style="mso-spacerun: &#39;yes&#39;; font-family: 微软雅黑; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 微软雅黑;">科技有限公司（以下均简称</span>“</span><span style="mso-spacerun: &#39;yes&#39;; font-family: 微软雅黑; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 微软雅黑;">智莲科技</span></span><span style="mso-spacerun: &#39;yes&#39;; font-family: 微软雅黑; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;">”）在此提醒您（以下称“您”或称“用户”）认真阅读理解本协议，包括免除或者限制</span><span style="mso-spacerun: &#39;yes&#39;; font-family: 微软雅黑; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 微软雅黑;">智莲科技</span></span><span style="mso-spacerun: &#39;yes&#39;; font-family: 微软雅黑; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 微软雅黑;">责任的免责条款及对您的权利限制条款；您确认，在您使用</span></span><span style="mso-spacerun: &#39;yes&#39;; font-family: 微软雅黑; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 微软雅黑;">智莲科技</span></span><span style="mso-spacerun: &#39;yes&#39;; font-family: 微软雅黑; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 微软雅黑;">的各项服务之前，您已充分阅读、理解并接受本协议的全部内容，一旦您在</span>“我已阅读并同意签署”前勾选，并点击“保存/确定/下一步”按钮，即表示您同意遵循本协议之所有约定，一旦您使用</span><span style="mso-spacerun: &#39;yes&#39;; font-family: 微软雅黑; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 微软雅黑;">智莲科技</span></span><span style="mso-spacerun: &#39;yes&#39;; font-family: 微软雅黑; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 微软雅黑;">的全部或部分服务</span>,亦表示您同意遵循本协议之所有约定。本协议在您和</span><span style="mso-spacerun: &#39;yes&#39;; font-family: 微软雅黑; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 微软雅黑;">智莲科技</span></span><span style="mso-spacerun: &#39;yes&#39;; font-family: 微软雅黑; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 微软雅黑;">之间具有合同上的法律效力。</span></span></p>
<p class="MsoNormal"><span style="mso-spacerun: &#39;yes&#39;; font-family: 微软雅黑; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 微软雅黑;">一、</span>&nbsp;<span style="font-family: 微软雅黑;">您同意通过本协议选定银行卡（以下简称</span>“银行卡”）在</span><span style="mso-spacerun: &#39;yes&#39;; font-family: 微软雅黑; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 微软雅黑;">智莲科技</span></span><span style="mso-spacerun: &#39;yes&#39;; font-family: 微软雅黑; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 微软雅黑;">平台与您在第三方支付机构的托管账户上进行绑定、开通快捷支付业务，即本协议所述的</span>“绑定”为扣款银行卡的确定，一旦绑定成功，第三方支付机构每次扣款前无需输入您绑定的银行卡账号、密码等信息，也无需您提交绑定的银行卡进行刷卡。</span></p>
<p class="MsoNormal"><span style="mso-spacerun: &#39;yes&#39;; font-family: 微软雅黑; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 微软雅黑;">二、</span>&nbsp;<span style="font-family: 微软雅黑;">您承诺上述选定的银行卡的开户证件信息与您身份证件信息完全一致。</span></span></p>
<p class="MsoNormal"><span style="mso-spacerun: &#39;yes&#39;; font-family: 微软雅黑; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 微软雅黑;">三、</span>&nbsp;<span style="font-family: 微软雅黑;">您允许</span></span><span style="mso-spacerun: &#39;yes&#39;; font-family: 微软雅黑; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 微软雅黑;">智莲科技</span></span><span style="mso-spacerun: &#39;yes&#39;; font-family: 微软雅黑; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 微软雅黑;">向快捷支付第三方支付机构发送您的信息（包括但不限于您的身份信息、银行信息、</span></span><span style="mso-spacerun: &#39;yes&#39;; font-family: 微软雅黑; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 微软雅黑;">智莲科技</span></span><span style="mso-spacerun: &#39;yes&#39;; font-family: 微软雅黑; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 微软雅黑;">注册信息等涉及您个人的各项信息）以便完成快捷支付业务。</span></span></p>
<p class="MsoNormal"><span style="mso-spacerun: &#39;yes&#39;; font-family: 微软雅黑; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 微软雅黑;">四、</span>&nbsp;</span><span style="mso-spacerun: &#39;yes&#39;; font-family: 微软雅黑; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 微软雅黑;">智莲科技</span></span><span style="mso-spacerun: &#39;yes&#39;; font-family: 微软雅黑; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 微软雅黑;">向第三方支付机构发送的您的一切信息是依据您自己主动填写的信息，</span></span><span style="mso-spacerun: &#39;yes&#39;; font-family: 微软雅黑; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 微软雅黑;">智莲科技</span></span><span style="mso-spacerun: &#39;yes&#39;; font-family: 微软雅黑; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 微软雅黑;">有权利但无义务审查您的银行卡信息与身份证件信息。</span></span><span style="mso-spacerun: &#39;yes&#39;; font-family: 微软雅黑; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 微软雅黑;">智莲科技</span></span><span style="mso-spacerun: &#39;yes&#39;; font-family: 微软雅黑; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 微软雅黑;">不对是否进行审查核实做出任何承诺，一切以您填写的信息为准。</span></span></p>
<p class="MsoNormal"><span style="mso-spacerun: &#39;yes&#39;; font-family: 微软雅黑; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 微软雅黑;">五、</span>&nbsp;<span style="font-family: 微软雅黑;">您必须按照第三方支付机构的快捷支付协议的要求绑定符合第三方支付机构要求的银行卡，并且您承诺是绑定的银行卡的合法持卡人（指银行卡账户的开户主体，下同）。</span></span></p>
<p class="MsoNormal"><span style="mso-spacerun: &#39;yes&#39;; font-family: 微软雅黑; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 微软雅黑;">六、</span>&nbsp;<span style="font-family: 微软雅黑;">其他有关绑定银行卡、开通快捷支付的权利义务详见您与第三方支付机构达成的快捷支付协议的各项约定。</span></span></p>
<p class="MsoNormal"><span style="mso-spacerun: &#39;yes&#39;; font-family: 微软雅黑; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 微软雅黑;">七、</span>&nbsp;<span style="font-family: 微软雅黑;">您与第三方支付机构因快捷支付相关事宜发生的争议与纠纷，请您按照您与第三方支付机构之间的快捷支付协议的约定解决，</span></span><span style="mso-spacerun: &#39;yes&#39;; font-family: 微软雅黑; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 微软雅黑;">智莲科技</span></span><span style="mso-spacerun: &#39;yes&#39;; font-family: 微软雅黑; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 微软雅黑;">不对您与第三方支付机构之间的争议承担任何责任。</span></span></p>
<p class="MsoNormal"><span style="mso-spacerun: &#39;yes&#39;; font-family: 微软雅黑; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 微软雅黑;">八、</span>&nbsp;<span style="font-family: 微软雅黑;">您的个人资料受到严格保护，不接受</span></span><span style="mso-spacerun: &#39;yes&#39;; font-family: 微软雅黑; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 微软雅黑;">智莲科技</span></span><span style="mso-spacerun: &#39;yes&#39;; font-family: 微软雅黑; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 微软雅黑;">、第三方支付机构、您银行卡开户行及您之外的任何个人或单位的查询请求。但法律法规（含行政规章、民族自治地方的自治条例和单行条例，下同）、司法机关、监管机构、你与第三方支付机构之前的快捷支付协议另有规定或要求，或为开通快捷支付之需要确有必要披露的除外。</span></span></p>
<p class="MsoNormal"><span style="mso-spacerun: &#39;yes&#39;; font-family: 微软雅黑; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 微软雅黑;">九、</span>&nbsp;<span style="font-family: 微软雅黑;">您承诺如果因您违反本协议或者与第三方支付机构之间的协议造成</span></span><span style="mso-spacerun: &#39;yes&#39;; font-family: 微软雅黑; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 微软雅黑;">智莲科技</span></span><span style="mso-spacerun: &#39;yes&#39;; font-family: 微软雅黑; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 微软雅黑;">损失的，</span></span><span style="mso-spacerun: &#39;yes&#39;; font-family: 微软雅黑; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 微软雅黑;">智莲科技</span></span><span style="mso-spacerun: &#39;yes&#39;; font-family: 微软雅黑; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 微软雅黑;">有权向你追究法律责任。</span></span></p>
<p class="MsoNormal">&nbsp;</p>
<p class="MsoNormal">授 权 人 ：{{$loanName}}</p>
<div><span style="color: #ffffff;">{{$kwBorrower}}</span></div>
<p>证件号码：{{$loanIdCard}}</p>
<p>手机号码：{{$loanMobile}}</p>
<p>授权日期：{{$signDate}}</p>
</div></div></body></html>