
<html data-server-rendered="true"><head><title>个人信息使用授权书</title></head> <style>
    td {
        border-left: 1px solid #000000 !important;
        border-top: 1px solid #000000 !important;
    }
    table {
        border-bottom: 1px solid #000000 !important;
        border-right: 1px solid #000000 !important;
    }

    body {
        font: '12px/1.5 Microsoft YaHei,Heiti SC,PingFang SC,tahoma,arial,Hiragino Sans GB,&quot;\5B8B\4F53&quot;,sans-serif';
        padding: 20px;
    }
</style> <body><div class="editor"><p><div class="Section0" style="layout-grid: 15.6000pt;">
    <p class="18" style="text-align: center;" align="center"><strong><span style="mso-spacerun: 'yes'; font-family: 微软雅黑; font-weight: bold; font-size: 14.0000pt; mso-font-kerning: 22.0000pt;"><span style="font-family: 微软雅黑;">个人信息使用授权书</span></span></strong></p>
    <p class="MsoNormal"><strong><span style="mso-spacerun: 'yes'; font-family: 微软雅黑; font-weight: bold; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 微软雅黑;">您同意并确认：</span></span></strong></p>
    <p class="MsoNormal" style="margin-left: 21.2500pt; mso-para-margin-left: 0.0000gd; text-indent: -21.2500pt; mso-char-indent-count: 0.0000; mso-list: l3 level1 lfo1;"><span style="font-family: 'Times New Roman'; mso-fareast-font-family: 微软雅黑; font-weight: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="mso-list: Ignore;">1.&nbsp;</span></span><span style="mso-spacerun: 'yes'; font-family: 微软雅黑; font-weight: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 微软雅黑;">您同意并授权</span></span><span style="mso-spacerun: 'yes'; font-family: 微软雅黑; font-weight: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 微软雅黑;">智莲（北京）</span></span><span style="mso-spacerun: 'yes'; font-family: 微软雅黑; font-weight: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 微软雅黑;">科技有限公司（或其委托或合作的第三方）在您申请借款、审批及贷后管理期间，通过查询服务提供机构向包含但不限于中国人民银行征信中心及其分支机构以及其他信息服务机构查询并获取您的个人信息（包括但不限于身份信息、联系方式、工作信息、银行卡交易信息、银行贷款相关信息、网络交易信息、逾期信息及其他信息等）【您已经充分理解并知晓该等信息被提供和使用的风险，包括但不限于：上述信息对您的信用评价、以及分析报告等结果产生不利影响的风险；该等信息被查询服务提供机构依法提供给</span></span><span style="mso-spacerun: 'yes'; font-family: 微软雅黑; font-weight: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 微软雅黑;">智莲（北京）</span></span><span style="mso-spacerun: 'yes'; font-family: 微软雅黑; font-weight: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 微软雅黑;">科技有限公司（或其委托或合作的第三方）后可能被第三方不当利用的风险；以及基于您的特定信用状况可能被不良信息骚扰的风险等。】，以了解您资信状况。对于在上述机构所获得的您信息仅在此笔贷款业务的贷前审核和贷后管理（贷款人向借款人发放贷款后直至该笔贷款结清时止的业务管理，包括但不限于贷后回访、还款监测、逾期催收等）中使用。</span>&nbsp;&nbsp;</span></p>
    <p class="MsoNormal" style="margin-left: 21.2500pt; mso-para-margin-left: 0.0000gd; text-indent: -21.2500pt; mso-char-indent-count: 0.0000; mso-list: l3 level1 lfo1;"><span style="font-family: 'Times New Roman'; mso-fareast-font-family: 微软雅黑; font-weight: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="mso-list: Ignore;">2.&nbsp;</span></span><span style="mso-spacerun: 'yes'; font-family: 微软雅黑; font-weight: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 微软雅黑;">您同意并授权包含但不限于中国人民银行征信中心及其分支机构以及其他信息服务机构可将其拥有的您信息通过查询服务提供给</span></span><span style="mso-spacerun: 'yes'; font-family: 微软雅黑; font-weight: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 微软雅黑;">智莲（北京）</span></span><span style="mso-spacerun: 'yes'; font-family: 微软雅黑; font-weight: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 微软雅黑;">科技有限公司（或其委托或合作的第三方）。同时，为刚好、更完整地展现您的资信情况，您同意并授权查询服务提供机构及其关联公司及其指定的第三方可留存、整理及加工本次获取的您信息用于查询服务提供机构及其关联公司及其指定的第三方为您提供的其他服务中。</span></span></p>
    <p class="MsoNormal" style="margin-left: 21.2500pt; mso-para-margin-left: 0.0000gd; text-indent: -21.2500pt; mso-char-indent-count: 0.0000; mso-list: l3 level1 lfo1;"><span style="font-family: 'Times New Roman'; mso-fareast-font-family: 微软雅黑; font-weight: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="mso-list: Ignore;">3.&nbsp;</span></span><span style="mso-spacerun: 'yes'; font-family: 微软雅黑; font-weight: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 微软雅黑;">您同意并授权，查询服务提供机构可将其合法获取的您的信息经过整合、加工并转化为信息评分或信息报告回传给</span></span><span style="mso-spacerun: 'yes'; font-family: 微软雅黑; font-weight: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 微软雅黑;">智莲（北京）</span></span><span style="mso-spacerun: 'yes'; font-family: 微软雅黑; font-weight: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 微软雅黑;">科技有限公司（或其委托或合作的第三方），用于您申请借款、审批及贷后管理等事项。</span></span></p>
    <p class="MsoNormal" style="margin-left: 21.2500pt; mso-para-margin-left: 0.0000gd; text-indent: -21.2500pt; mso-char-indent-count: 0.0000; mso-list: l3 level1 lfo1;"><span style="font-family: 'Times New Roman'; mso-fareast-font-family: 微软雅黑; font-weight: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="mso-list: Ignore;">4.&nbsp;</span></span><span style="mso-spacerun: 'yes'; font-family: 微软雅黑; font-weight: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 微软雅黑;">您同意并授权</span></span><span style="mso-spacerun: 'yes'; font-family: 微软雅黑; font-weight: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 微软雅黑;">智莲（北京）</span></span><span style="mso-spacerun: 'yes'; font-family: 微软雅黑; font-weight: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 微软雅黑;">科技有限公司（或其委托或合作的第三方）通过查询服务提供机构向包括但不限于中国人民银行征信中心及其分支机构以及其他信息服务机构上传您在本次借款过程生成的资信信息。同时，您同意并授权包括但不限于中国人民银行征信中心及其分支机构以及其他信息服务机构接收</span></span><span style="mso-spacerun: 'yes'; font-family: 微软雅黑; font-weight: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 微软雅黑;">智莲（北京）</span></span><span style="mso-spacerun: 'yes'; font-family: 微软雅黑; font-weight: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 微软雅黑;">科技有限公司（或其委托或合作的第三方）通过查询服务提供机构上传的您在本次借款过程生成的资信信息。</span></span></p>
    <p class="MsoNormal" style="margin-left: 21.2500pt; mso-para-margin-left: 0.0000gd; text-indent: -21.2500pt; mso-char-indent-count: 0.0000; mso-list: l3 level1 lfo1;"><span style="font-family: 'Times New Roman'; mso-fareast-font-family: 微软雅黑; font-weight: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="mso-list: Ignore;">5.&nbsp;</span></span><span style="mso-spacerun: 'yes'; font-family: 微软雅黑; font-weight: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 微软雅黑;">为更好地为您提供服务，您同意并授权查询服务机构可与其合作的第三方进行联合研究，并可将通过本授权书获得的您的信息投入到该等联合研究中。但查询服务机构与其合作的第三方在开展上述联合研究前，应要求其合作的第三方对在联合研究中所获取的您的信息予以保密。</span></span></p>
    <p class="MsoNormal" style="margin-left: 21.2500pt; mso-para-margin-left: 0.0000gd; text-indent: -21.2500pt; mso-char-indent-count: 0.0000; mso-list: l3 level1 lfo1;"><span style="font-family: 'Times New Roman'; mso-fareast-font-family: 微软雅黑; font-weight: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="mso-list: Ignore;">6.&nbsp;</span></span><span style="mso-spacerun: 'yes'; font-family: 微软雅黑; font-weight: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 微软雅黑;">本授权书可在您接收</span></span><span style="mso-spacerun: 'yes'; font-family: 微软雅黑; font-weight: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 微软雅黑;">智莲（北京）</span></span><span style="mso-spacerun: 'yes'; font-family: 微软雅黑; font-weight: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 微软雅黑;">科技有限公司（或其委托或合作的第三方）提供服务（包括贷前审核和贷后管理）的过程中多次使用，</span></span><span style="mso-spacerun: 'yes'; font-family: 微软雅黑; font-weight: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 微软雅黑;">智莲（北京）</span></span><span style="mso-spacerun: 'yes'; font-family: 微软雅黑; font-weight: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 微软雅黑;">科技有限公司（或其委托或合作的第三方）及查询服务提供机构自您签署本授权之日起可多次依据本授权书而操作执行本授权书项下的活动无需您另行授权。</span></span></p>
    <p class="MsoNormal" style="margin-left: 21.2500pt; mso-para-margin-left: 0.0000gd; text-indent: -21.2500pt; mso-char-indent-count: 0.0000; mso-list: l3 level1 lfo1;"><span style="font-family: 'Times New Roman'; mso-fareast-font-family: 微软雅黑; font-weight: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="mso-list: Ignore;">7.&nbsp;</span></span><span style="mso-spacerun: 'yes'; font-family: 微软雅黑; font-weight: normal; font-size: 10.5000pt; mso-font-kerning: 1.0000pt;"><span style="font-family: 微软雅黑;">您确认已充分被告知、了解并接受上述授权的法律后果。</span></span></p>
    <p class="MsoNormal" style="mso-para-margin-left: 0.0000gd;">&nbsp;</p>
    <p>授 权 人 ：{{$loanName}}</p>
    <div><span style="color: #ffffff;">{{$kwBorrower}}</span></div>
    <p>证件号码：{{$loanIdCard}}</p>
    <p>手机号码：{{$loanMobile}}</p>
    <p>授权日期：{{$signDate}}</p>
</div></body></html>